---
title: "Comandos das aulas do curso"
output:
  html_document:
    toc: false
    code_folding: show
---

```{r setup, include=FALSE, cache=FALSE}
#source("setup_knitr.R")
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA,
                      warning = FALSE,
                      message = FALSE)
```


```{css, echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
.toc-content {
padding-left: 0;
padding-right: 0;
margin-left: -95px;
}
table.dataTable thead th {
text-align: left;
}
table.dataTable tbody th, table.dataTable tbody td {
padding: 8px 18px;
}
table.dataTable thead th, table.dataTable thead td {
padding: 8px 18px 8px 18px;
border-bottom: 1px solid #111;
}
body {
font-family: Roboto;
font-size: 14px;
line-height: 1.529;
}
h1.title {
padding-top: 30px;
top: 34px;
left: 390px;
width: 832px;
height: 77px;
text-align: left;
letter-spacing: 1px;
color: #000000;
opacity: 1;
margin: 0;
font-size: 30px;
line-height: 47px;
font-family: 'Roboto', sans-serif;
display: inline-block;
max-width: 100%;
}
h4.date {
font-family: "Roboto Mono", Roboto, sans-serif;
font-size: 20px;
color: #000000;
line-height: 26px;
font-weight: 400;
letter-spacing: 0;
}
body::before {
content: '';
height: 168px;
width: 100%;
position: absolute;
top: 0;
left: 0;
background: #FFFAFA;
z-index: -1;
}

@media only screen and (min-width: 1600px) {
#header {
background: url(http://www.utfpr.edu.br/icones/cabecalho/logo-utfpr/@@images/image.png) #FFFAFA right center no-repeat padding-box;
background-size: 210px;
}
```
<br>
<br>
<br>

Abaixo estão os comandos do `R` utilizados durante as aulas.


## Módulo 1 - Probabilidade

- **Aula 01** - $01/09/2020$:

### Primiro exemplo
```{r}
x <- c(1,2,3,4,5,6,7,80)
x
class(x)
x[8]
X <- matrix(data= c(1,2,3,4),ncol = 2, byrow=TRUE)
X
Y <- matrix(c(2,4,5,8,6,8),ncol=2, byrow = TRUE)
Y
Y%*%X
Y[1,2]
```
### Funções estatística básica
```{r est_basica}
x <- rnorm(100)
head(x,n=3)
tail(x,n=3)

#### Media = somatório x_i/n
media <- function(x){
    soma = 0
    for(i in 1:length(x))
        soma = soma + x[i]
    media = soma/length(x)
    return(media)
}
media(x)

mean(x)
```

#### Intervalo de confiança
```{r IC}
# LI = media - Z*desvio_padrão/raiz(n)
# LS = media + Z*desvio_padrão/raiz(n)
IC <- function(x, conf = 0.95){
    avg = media(x)
    z = c(-qnorm(conf),qnorm(conf))
    dp = sd(x)
    n = length(x)
    raizn <- sqrt(n)
    #li = avg - z*(dp/raizn)
    #ls = avg + z*(dp/raizn)
    ic  <- avg + z*(dp/raizn)
    return(paste("IC(95%)= ",  ic))
}
IC(x)
```

#### Exemplo de acesso a dados
```{R dados}
### Listando arquivos
dir(pattern = '.csv')

dados <- read.csv("hospital.csv",
                  header = TRUE, sep ='\t')
head(dados)
dim(dados)
str(dados)
```

### Sumário dos dados
```{r summary}
media(dados$idade)
names(dados)
var_num <- dados[,c(1,3:8)]
str(var_num)

summary(dados$idade)

for(i in 1:length(names(var_num))){
    print(summary(var_num[i]))
    }
```

## Gráficos
```{r graph}
plot(var_num$idade)
hist(var_num$idade)

par(mfrow=c(2,4))
lapply(var_num,hist)

```

#### ggplot2
### lattice
```{R,ggplot}
library(ggplot2)

var_num$id <- 1:dim(var_num)[1]
df <- reshape2::melt(var_num, id.vars = 'id', variable.name = "serie")
ggplot(df, aes(id,value)) +
    geom_line(aes(colour = serie)) +
    facet_grid(serie ~ .)
```

##### Probabilidade
#### Exemplo de espaço amostra
```{R omega1}
## Lançamento de dois dados
6^2
amostral <- 1:6
amostral

n <- 3000
sorteio <- NULL
for(i in 1:n)
    sorteio <- c(sorteio,paste(sample(x = amostral,
                                      replace = TRUE,
                                size = 2),collapse =""))

length(unique(sorteio))
sorteio <- sort(unique(sorteio))
sorteio

## Lançamento de três dados
6^3
n <- 3000
sorteio2 <- NULL
for(i in 1:n)
    sorteio2 <- c(sorteio2,paste(sample(x = amostral,
                                      replace = TRUE,
                                size = 3),collapse =""))

length(unique(sorteio2))
sorteio2 <- sort(unique(sorteio2))
sorteio2
```

### Exemplo definição clássica de probab.
```{R defClass}
### E1= (1,1)
library(prob)


#a <- urnsamples(amostral,
#           size = 2,
#           replace = TRUE)

amostral
sorteio2
dado1 <- substr(sorteio,1,1)
dado2 <- substr(sorteio,2,2)
iguais <- ifelse(dado1 == dado2, sorteio,"excluir")
iguais
iguais <- iguais[iguais != "excluir"]
PE1 <- length(iguais)/length(sorteio)
PE1

```
