---
title: "Referências Bibliográficas"
output:
  html_document:
    toc: false
---


```{css,echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
.toc-content {
padding-left: 0;
padding-right: 0;
margin-left: -95px;
}
table.dataTable thead th {
text-align: left;
}
table.dataTable tbody th, table.dataTable tbody td {
padding: 8px 18px;
}
table.dataTable thead th, table.dataTable thead td {
padding: 8px 18px 8px 18px;
border-bottom: 1px solid #111;
}
body {
font-family: Roboto;
font-size: 14px;
line-height: 1.529;
}
h1.title {
padding-top: 30px;
top: 34px;
left: 390px;
width: 832px;
height: 77px;
text-align: left;
letter-spacing: 1px;
color: #000000;
opacity: 1;
margin: 0;
font-size: 30px;
line-height: 47px;
font-family: 'Roboto', sans-serif;
display: inline-block;
max-width: 100%;
}
h4.date {
font-family: "Roboto Mono", Roboto, sans-serif;
font-size: 20px;
color: #000000;
line-height: 26px;
font-weight: 400;
letter-spacing: 0;
}
body::before {
content: '';
height: 168px;
width: 100%;
position: absolute;
top: 0;
left: 0;
background: #FFFAFA;
z-index: -1;
}

@media only screen and (min-width: 1600px) {
#header {
background: url(http://www.utfpr.edu.br/icones/cabecalho/logo-utfpr/@@images/image.png) #FFFAFA right center no-repeat padding-box;
background-size: 210px;
}
```

<br>
<br>
<br>

## Referências básicas

- Bussab, WO; [Morettin, PA](http://www.ime.usp.br/~pam).
  [Estatística Básica](http://www.editorasaraiva.com.br/produtos/show/isbn:9788502207998/titulo:estatistica-basica/).
  São Paulo: [Editora Saraiva](http://www.saraivauni.com.br), 2017 (9ª Edição).
  
- Kolmogorov, AN;
  [Foundations of the theory of probability](https://books.google.com.br/books?id=ySZSDwAAQBAJ&hl=pt-BR).
  New York, USA: Chelsea Publishing Company, 1956 (2ª Edição).  
  
- [Magalhães, MN](http://www.ime.usp.br/~marcos);
      [Lima, ACP](http://www.ime.usp.br/~acarlos).
      [Noções de Probabilidade e Estatística](http://www.ime.usp.br/~noproest).
      São Paulo: EDUSP, 2015 (7ª edição).
      
- [Magalhães, MN](http://www.ime.usp.br/~marcos);
      [Probabilidade e variáveis aleatórias](http://www.ime.usp.br/~noproest).
      São Paulo: EDUSP, 2006 (2ª edição).
      
- Meyer, PL;
      [Probabilidade: aplicações à estatística](https://www.amazon.com.br/Probabilidade-Aplica%C3%A7%C3%B5es-Estat%C3%ADstica-Paul-Meyer/dp/8521602944).
      Rio de Janeiro: LTC, 1983 (2ª edição).      
      
- Montgomery, DC; Runger, GC.
  [Estatística aplicada e probabilidade para engenheiros](http://www.grupogen.com.br/estatistica-aplicada-e-probabilidade-para-engenheiros).
  Rio de Janeiro: LTC Editora, 2012 (5ª Edição).

## Referências complementares

- Andrade, DF; Ogliari, PJ.
  [Estatística para as ciências agrárias e biológicas, com noções de experimentação](http://www.editora.ufsc.br/publicacao/detalhe/id/537). Florianópolis: Editora da UFSC, 2013.
- Dantas, CAB.
  [Probabilidade: um curso introdutório](http://www.edusp.com.br/detlivro.asp?id=41384).
  São Paulo: EDUSP, 2008.
- Morettin, LG.
  [Estatística básica: probabilidade e inferência](http://loja.pearson.com.br/estatistica-basica-probabilidade-e-inferencia-9788576053705/p).
  São Paulo: Pearson, 2010.
- Navidi, W.
  [Probabilidade e estatística para ciências exatas](http://www.grupoa.com.br/livros/matematica-e-estatistica/probabilidade-e-estatistica-para-ciencias-exatas/9788580550733).
  Porto Alegre: Bookman, 2012.
- Spiegel, MR; Schiller, J; Srinivasan, A.
  [Probabilidade e estatística](http://www.grupoa.com.br/livros/matematica-e-estatistica/probabilidade-e-estatistica/9788565837187).
  Porto Alegre: Bookman, 2013.
- **Nota:** existem diversos textos de estatística compatíveis com o
      programa do curso. Consulte o professor sobre a adequação de
      qualquer outra referência bibliográfica.

## Referências *online*

- [Coursera](https://pt.coursera.org)
- [Kahn Academy](http://www.khanacademy.org) vídeos sobre diversos
      assuntos, incluindo sessões especificas de estatística e
      probabilidade.
- [Udacity Online courses](http://www.udacity.com). Ver em particular:
    - [Introduction to Statistics](https://www.udacity.com/course/st101)

## Leituras complementares

- Hilborn, R; Mangel, M.
  [The ecological detective: confronting models with data](http://press.princeton.edu/titles/5987.html).
  Princeton University Press, 1997.
- Huff, D.
  [Como mentir com estatística](http://www.intrinseca.com.br/livro/624/).
  Rio de Janeiro: Intrínseca, 2016.
- Mlodinow, L.
  [O andar do bêbado. Como o acaso determina nossas vidas](http://zahar.com.br/livro/o-andar-do-b%C3%AAbado).
  Rio de Janeiro: Zahar, 2009.
- Oakley, B.
  [Aprendendo a aprender. Como ter sucesso em matemática, ciências ou qualquer outra matéria](http://www.infopress.com.br).
  São Paulo: Infopress, 2015.
- Pólya, G.
  [How to solve it](https://www.penguin.co.uk/books/12619/how-to-solve-it).
  London: Penguin Books, 1990.
- Salsburg, D.
  [Uma senhora toma chá. Como a estatística revolucionou a ciência no século XX](http://www.zahar.com.br/livro/uma-senhora-toma-cha).
  Rio de Janeiro: Zahar, 2009.
- Wheelan, C.
  [Estatística: o que é, para que serve, como funciona](http://www.zahar.com.br/livro/estatistica).
  Rio de Janeiro: Zahar, 2016.
